version: "2.2"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
#    volumes:
#      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile.aws
    command: bash -c "sh /app/entrypoints/docker-entrypoint-web.sh"
    # volumes:
    #   - ./app:/app/app
    ports:
      - "80:3000"
    environment:
      RAILS_ENV: production
      PG_USERNAME: myuser
      PG_PASSWORD: mypass
      PG_HOST: db
      REDIS_URL: "redis://redis:6379/1"
      WS_CONNECTION_URL: "ws://myconnect.dssigmadev.link:28080/cable"
    depends_on:
      - db
      - redis
  websocket:
    build:
      context: .
      dockerfile: Dockerfile.aws
    command: bash -c "sh /app/entrypoints/docker-entrypoint-websocket.sh"
    ports:
      - "28080:28080"
    environment:
      RAILS_ENV: production
      PG_USERNAME: myuser
      PG_PASSWORD: mypass
      PG_HOST: db
      REDIS_URL: "redis://redis:6379/1"
    depends_on:
      - db
      - redis
